CREATE TABLE IF NOT EXISTS PRODUCT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    SALES_UNITS INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_STOCK(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    SIZE VARCHAR NOT NULL,
    QUANTITY INT NOT NULL
);